import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import wabtFactory from 'wabt';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT_DIR = path.resolve(__dirname, '..');

async function buildWasm() {
  const watPath = path.join(ROOT_DIR, 'src', 'wasm', 'dsp_kernel.wat');
  const wasmPath = path.join(ROOT_DIR, 'src', 'wasm', 'dsp_kernel.wasm');
  const tsBinaryPath = path.join(ROOT_DIR, 'src', 'wasm', 'dsp_kernel_binary.ts');

  console.log(`[build-wasm] Reading WAT source: ${watPath}`);
  const watSource = fs.readFileSync(watPath, 'utf8');

  console.log('[build-wasm] Initializing WABT (WebAssembly Binary Toolkit)...');
  const wabt = await wabtFactory();

  const parsed = wabt.parseWat('dsp_kernel.wat', watSource, {
    mutable_globals: true,
    sat_float_to_int: true,
    sign_extension: true,
    simd: true
  });

  const { buffer } = parsed.toBinary({
    log: false,
    write_debug_names: true
  });

  parsed.destroy();

  const uint8Buffer = Buffer.from(buffer);
  fs.writeFileSync(wasmPath, uint8Buffer);
  console.log(`[build-wasm] Emitted WASM binary: ${wasmPath} (${uint8Buffer.byteLength} bytes)`);

  // Generate self-contained TypeScript binary module with base64 encoding
  // for seamless execution across Node.js/Vitest and Vite web bundle.
  const base64Str = uint8Buffer.toString('base64');
  const tsCode = `// Auto-generated by scripts/build-wasm.mjs — DO NOT EDIT DIRECTLY
export const DSP_WASM_BASE64 = '${base64Str}';

export function getDspWasmBytes(): Uint8Array {
  if (typeof Buffer !== 'undefined') {
    return new Uint8Array(Buffer.from(DSP_WASM_BASE64, 'base64'));
  }
  const binaryString = atob(DSP_WASM_BASE64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}
`;

  fs.writeFileSync(tsBinaryPath, tsCode, 'utf8');
  console.log(`[build-wasm] Emitted TypeScript binary wrapper: ${tsBinaryPath}`);
  console.log('[build-wasm] WASM build completed successfully!');
}

buildWasm().catch((err) => {
  console.error('[build-wasm] Fatal build error:', err);
  process.exit(1);
});
